#!/bin/bash
# Created by the VLSCI job script generator for SLURM on x86
# Wed Oct 09 2013 16:18:26 GMT+1100 (EST)

# Partition for the job:
#SBATCH -p main

# The name of the job:
#SBATCH --job-name="jwikst-zombie-test"

# Maximum number of CPU cores used by the job:
#SBATCH --ntasks=128

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-0:50:00

# Run the job from the directory where it was launched (default):
# The job command(s):
mpirun -mca btl ^openib -np 128 --mca orte_base_help_aggregate 0 ./main $1 $2 $3 $4 $5 $6
