#!/bin/bash
# Created by the VLSCI job script generator
# Wed Oct 09 2013 16:28:02 GMT+1100 (EST)

# The name of the job:
#SBATCH --job-name="jwikst-zombies"

# Send yourself an email when the job:
# aborts abnormally (fails)
#SBATCH --mail-type=FAIL
# ends successfully
#SBATCH --mail-type=END

# Number of BlueGene compute nodes used by the job (multiply by 16 to get CPU cores):
#SBATCH --nodes=4

# The maximum running time of the job in days-hours:mins
#SBATCH --time=0-0:30

# The job command(s):
srun --ntasks=64 ./main

